---
- hosts: all
  gather_facts: no
  remote_user: dbadmin

- name: Setup of HAProxy
  import_playbook: ./playbooks/setup_haproxy.yml

- name: Setup of Consul
  import_playbook: ./playbooks/setup_consul.yml        

- name: Setup of PostgreSQL
  import_playbook: ./playbooks/setup_postgresql.yml

- name: Setup of Patroni in main cluster
  import_playbook: ./playbooks/setup_patroni.yml

- name: Setup of Patroni in standby cluster
  import_playbook: ./playbooks/setup_patroni_stby.yml