---
- hosts: all

- name: Setup of etcd
  hosts: etcd
  remote_user: dbadmin
  gather_facts: no
  become: yes
  
  tasks:

  - name: Loading variables
    include_vars:
      file: ./variables.yml
      name: var

  - name: Download and extract etcd binaries
    unarchive:
      src: https://github.com/etcd-io/etcd/releases/download/v3.4.16/etcd-v3.4.16-linux-amd64.tar.gz
      dest: /tmp/
      remote_src: yes
  
  - name: Copying etcd binaries to /usr/local/bin
    copy:
      src: /tmp/etcd-v3.4.16-linux-amd64/{{item}}
      dest: /usr/local/bin/
      mode: 0755
      remote_src: yes
    loop:
      - etcd
      - etcdctl

  - name: etcd configuration folders
    file:
      path: "{{item}}"
      state: directory
      mode: 0755
    loop:
      - /var/lib/etcd/
      - /etc/etcd/

  - name: Creating etcd user
    user:
      name: etcd
      shell: /sbin/nologin

  - name: Setting ownership of etcd folder
    file:
      path: /var/lib/etcd/
      owner: etcd
      group: etcd

  - name: Creating etcd service
    copy:
      src: ../files/etcd.service
      dest: /etc/systemd/system/etcd.service

  - name: etcd configuration file
    copy:
      dest: /etc/default/etcd
      content: |
        ETCD_LISTEN_PEER_URLS="http://{{ var.etcd_vm_private_ip }}:2380,http://127.0.0.1:7001"
        ETCD_LISTEN_CLIENT_URLS="http://127.0.0.1:2379, http://{{ var.etcd_vm_private_ip }}:2379"
        ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{ var.etcd_vm_private_ip }}:2380"
        ETCD_INITIAL_CLUSTER="etcd0=http://{{ var.etcd_vm_private_ip }}:2380,"
        ETCD_ADVERTISE_CLIENT_URLS="http://{{ var.etcd_vm_private_ip }}:2379"
        ETCD_INITIAL_CLUSTER_TOKEN="pgsql-vm"
        ETCD_INITIAL_CLUSTER_STATE="new"
      mode: 0644

  - name: Starting etcd service
    systemd:
      daemon_reload: yes
      state: started
      name: etcd
      enabled: yes

- name: Setup of HAProxy
  hosts: haproxy
  gather_facts: no
  remote_user: dbadmin
  become: yes

  tasks:

    - name: Setting SELinux in Permissve mode
      selinux:
        policy: targeted
        state: permissive
    
    - name: Installing HAProxy package
      dnf:
        name: haproxy
        state: latest

    - name: Copying haproxy.cfg
      copy:
        src: ../files/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644

    - name: Restarting HAProxy service
      systemd:
        name: haproxy
        state: restarted